import Head from "next/head";

const _Head = () => {
  return (
    <Head>
      <title>NxtAto</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};

export default _Head;
